[project]
authors = ["Michael Hess <michaelhess17@yahoo.com>"]
channels = ["conda-forge", "pytorch", "nvidia", "https://repo.prefix.dev/julia-forge"]
description = "Neural ODE models used for studying the dynamical stability of walking animals"
name = "NeuralODE"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[system-requirements]
cuda = "12.4"

[tasks]

[dependencies]
python = ">=3.12.0,<4"
pytorch = ">=2.4.1,<3"
torchvision = ">=0.19.1,<0.20"
jupyterlab = ">=4.2.5,<5"
matplotlib = ">=3.9.2,<4"
tqdm = ">=4.66.5,<5"
torchdiffeq = ">=0.2.2,<0.3"
ray-tune = ">=2.37.0,<3"
ipywidgets = ">=8.1.5,<9"
seaborn = ">=0.13.2,<0.14"
polars = ">=1.9.0,<2"
git = ">=2.47.0,<3"
