[project]
authors = ["Michael Hess <michaelhess17@yahoo.com>"]
channels = ["conda-forge", "pytorch", "nvidia"]
description = "Neural ODE models used for studying the dynamical stability of walking animals"
name = "NeuralODE"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[system-requirements]
#cuda = "12.6"

[tasks]

[dependencies]
python = "*"
pytorch = "*"
torchvision = "*"
jupyterlab = "*"
matplotlib = "*"
tqdm = "*"
torchdiffeq = "*"
ray-tune = "*"
ipywidgets = "*"
seaborn = "*"
polars = "*"
git = "*"
pip = "*"
scikit-learn = "*"
jupyter = "*"
resample = ">=1.10.1,<2"
numpy = ">=2.1.2,<3"
pytest = ">=8.3.3,<9"

[pypi-dependencies]
jax = { version = "*", extras = ["cuda12"] }
diffrax = "*"
optax = "*"
ddfa_node = { path = "./DDFA_NODE", editable = true}
delase = { path = "../delase", editable = true}
