[project]
authors = ["Michael Hess <michaelhess17@yahoo.com>"]
channels = ["conda-forge", "pytorch", "nvidia"]
description = "Neural ODE models used for studying the dynamical stability of walking animals"
name = "NeuralODE"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[system-requirements]
cuda = "12.6"

[tasks]

[dependencies]
python = "*"
pytorch = "*"
torchvision = "*"
jupyterlab = "*"
matplotlib = "*"
tqdm = "*"
torchdiffeq = "*"
ray-tune = "*"
ipywidgets = "*"
seaborn = "*"
polars = "*"
git = "*"
pip = "*"
scikit-learn = "*"
jupyter = "*"
resample = ">=1.10.1,<2"

[pypi-dependencies]
jax = { version = "*", extras = ["cuda12"] }
diffrax = "*"
optax = "*"


# Also have installed DeLASE from my fork on github
# https://github.com/michaelhess17/DeLASE
# `git clone https://github.com/michaelhess17/DeLASE.git`
# `cd DeLASE`
# `python -m pip install -e .`

# Also have installed ddfa_node from my fork on github
# https://github.com/michaelhess17/ddfa_node
# `git clone https://github.com/michaelhess17/ddfa_node.git`
# `cd ddfa_node`
# `python -m pip install -e .`
