[project]
authors = ["Michael Hess <Michaelhess17@yahoo.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "NeuralODE"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
seaborn = ">=0.13.2,<0.14"
polars = ">=1.17.1,<2"
numpy = ">=2.2.0,<3"
matplotlib = ">=3.10.0,<4"
scikit-learn = ">=1.6.0,<2"
resample = ">=1.10.1,<2"
tqdm = ">=4.67.1,<5"
ipython = ">=8.31.0,<9"
ray-core = ">=2.42.0,<3"
ray-train = ">=2.42.0,<3"
ray-tune = ">=2.42.0,<3"
ray-data = ">=2.42.0,<3"

[pypi-dependencies]
jax = {version = "*", extras = ["cuda12_pip"]}
diffrax = ">=0.6.1, <0.7"
optax = ">=0.2.4, <0.3"
ddfa_node = { path = "./DDFA_NODE", editable = true}
#delase = { path = "../delase", editable = true}
